// ==========================================================================
// CENTRAL EXAM INTERFACE MASTER BACKEND ENGINE (server.js)
// ==========================================================================
const express = require('express');
const cors = require('cors');
const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

// CENTRAL DATA VAULT (90 Entirely Distinct Syllabus Questions)
const backendQuizDatabase = {
  
  "subject-dbms": [
    { id: 1, question: "Which normal form condition does a relation violate due to a transitive dependency among non-prime attributes?", options: ["1NF", "2NF", "3NF", "BCNF"], answer: "3NF" },
    { id: 2, question: "During transaction execution under a 2-Phase Locking (2PL) protocol, what happens once a transaction enters its shrinking phase?", options: ["It can acquire new locks but cannot release any", "It can release existing locks but is strictly forbidden from acquiring new ones", "It must immediately commit all database updates to the disk", "It releases all locks simultaneously in a single atomic cycle"], answer: "It can release existing locks but is strictly forbidden from acquiring new ones" },
    { id: 3, question: "Which relational algebra operational symbol represents the 'PROJECT' vertical attribute filter?", options: ["Sigma (σ)", "Pi (π)", "Join (⨝)", "Rho (ρ)"], answer: "Pi (π)" },
    { id: 4, question: "What transaction isolation reading anomaly occurs when a transaction reads data modified by another parallel transaction that has not committed yet?", options: ["Non-repeatable Read", "Dirty Read", "Phantom Read", "Lost Update"], answer: "Dirty Read" },
    { id: 5, question: "In database storage architectures, what is the primary advantage of a B+ Tree index over a standard BST?", options: ["It ensures records are fully encrypted on disk", "It maintains a low height-balanced fan-out, minimizing random disk I/O for range queries", "It completely eliminates the processing overhead of structural locking", "It processes string evaluations faster using linear arrays"], answer: "It maintains a low height-balanced fan-out, minimizing random disk I/O for range queries" },
    { id: 6, question: "Which ACID property guarantees that all database updates made by a successfully committed transaction persist permanently, even in the event of a total system crash?", options: ["Atomicity", "Consistency", "Isolation", "Durability"], answer: "Durability" },
    { id: 7, question: "In a relational database model, a candidate key that is not chosen to be the primary key of a table is specifically referred to as a:", options: ["Foreign Key", "Super Key", "Alternate Key", "Surrogate Key"], answer: "Alternate Key" },
    { id: 8, question: "The SQL 'HAVING' clause is fundamentally distinguished from the 'WHERE' clause because it filters row rows based on:", options: ["Individual row condition checks", "Aggregate function summary group conditions", "Primary key indexing parameters", "Foreign key constraints mapping values"], answer: "Aggregate function summary group conditions" },
    { id: 9, question: "Which log-based database recovery scheme writes database updates to the physical disk media only AFTER a transaction reaches its formal commit point?", options: ["Deferred Update technique", "Immediate Update technique", "Shadow Paging mechanism", "Asynchronous Cache Dumping"], answer: "Deferred Update technique" },
    { id: 10, question: "What structural rule constraint does a database engine enforce when a foreign key is declared with an 'ON DELETE CASCADE' reference option?", options: ["It blocks parent row deletions completely if child records exist", "It automatically deletes child table rows whenever the referenced parent row is dropped", "It sets child foreign key cell properties to NULL dynamically", "It creates an alert flag entry trace inside system logs"], answer: "It automatically deletes child table rows whenever the referenced parent row is dropped" },
    { id: 11, question: "A relational schema is strictly verified to be in Boyce-Codd Normal Form (BCNF) if, for every non-trivial functional dependency X -> Y, X is a:", options: ["Prime Attribute", "Super Key", "Foreign Key", "Candidate Attribute component"], answer: "Super Key" },
    { id: 12, question: "Which indexing approach physically alters or dictates the actual storage sequential sorting order of data rows on the disk surface?", options: ["Clustered Index", "Non-Clustered Index", "Secondary Index", "B-Tree Node Pointer Array"], answer: "Clustered Index" },
    { id: 13, question: "The relational algebra operator 'NATURAL JOIN' (⨝) implicitly links two tables together based on which matching criteria?", options: ["Primary keys to foreign keys explicitly", "All attributes that share the exact same column names in both schemas", "User-specified inequality conditions (<, >)", "The absolute physical layout index of rows"], answer: "All attributes that share the exact same column names in both schemas" },
    { id: 14, question: "What concurrency control problem occurs when two parallel transactions read the exact same memory row, and then both update it based on their initial reads, wiping out one update?", options: ["Dirty Read state", "Unrepeatable Read pattern", "Lost Update anomaly", "Phantom Read conflict"], answer: "Lost Update anomaly" },
    { id: 15, question: "To satisfy the rigorous constraints of the Second Normal Form (2NF), a relation table layout must already be in 1NF and must completely eliminate which tracking anomaly?", options: ["Transitive Dependencies", "Partial Dependencies", "Overlapping Candidate Keys", "Referential Integrity Violations"], answer: "Partial Dependencies" }
  ],

  "subject-dm": [
    { id: 16, question: "Let G be a simple undirected graph with 8 vertices. If every vertex has a uniform degree of 3, what is the exact number of edges sitting in G?", options: ["24 edges", "12 edges", "8 edges", "16 edges"], answer: "12 edges" },
    { id: 17, question: "Consider an algebraic structure (G, *) where G is a finite set. To qualify specifically as an Abelian Group, which property must it hold beyond standard group axioms?", options: ["The existence of a unique identity element", "The commutative property: a * b = b * a for all a, b in G", "The condition that every element must be its own self-inverse", "The associative mapping condition"], answer: "The commutative property: a * b = b * a for all a, b in G" },
    { id: 18, question: "A partially ordered set (Poset) (A, <=) is structurally classified as a 'Lattice' if and only if every pair of elements has which properties?", options: ["A unique lower bound only", "Both a Greatest Lower Bound (GLB) and a Least Upper Bound (LUB)", "A strict linear chain order", "A maximal and minimal boundary sequence matrix"], answer: "Both a Greatest Lower Bound (GLB) and a Least Upper Bound (LUB)" },
    { id: 19, question: "In propositional logic, if a compound proposition is structurally true for all possible truth configurations of its component variables, it is termed a:", options: ["Contradiction", "Contingency", "Tautology", "Valid Satisfiability Predicate"], answer: "Tautology" },
    { id: 20, question: "Under Euler's formula for connected planar graphs, if a graph has 12 vertices and 8 regions/faces, how many edges must it contain?", options: ["14 edges", "18 edges", "20 edges", "16 edges"], answer: "18 edges" },
    { id: 21, question: "According to the Principle of Inclusion-Exclusion, for three finite sets A, B, and C, the expression for |A U B U C| subtracts which intersections first?", options: ["The triple intersection |A n B n C|", "The double intersections: |A n B| + |B n C| + |A n C|", "The individual set sizes: |A| + |B| + |C|", "No values are subtracted in this theorem expansion"], answer: "The double intersections: |A n B| + |B n C| + |A n C|" },
    { id: 22, question: "A graph is structurally defined as a Tree if it satisfies which minimal combined set of topological criteria?", options: ["It is directed and has regular vertex degree bounds", "It is connected and contains no simple cycles (acyclic)", "It contains an even number of vertices and matching parallel faces", "It can be parsed completely into a bipartite Hamiltonian path alignment"], answer: "It is connected and contains no simple cycles (acyclic)" },
    { id: 23, question: "What is the total number of unique binary relations that can be defined from a set A containing 3 elements to a set B containing 2 elements?", options: ["2^5 relations", "2^6 relations", "6^2 relations", "5^2 relations"], answer: "2^6 relations" },
    { id: 24, question: "What is the maximum number of edges possible in a simple connected planar graph containing v vertices, where v >= 3?", options: ["3v - 6", "2v - 4", "3v + 6", "v(v-1)/2"], answer: "3v - 6" },
    { id: 25, question: "Which properties must a relation R defined on a set A satisfy simultaneously to be classified as a strict Equivalence Relation?", options: ["Reflexive, Symmetric, and Transitive", "Reflexive, Anti-symmetric, and Transitive", "Irreflexive, Symmetric, and Asymmetric", "Closure, Identity, and Inverse"], answer: "Reflexive, Symmetric, and Transitive" },
    { id: 26, question: "How many unique vertices does a regular graph have if it has 15 edges and every vertex has a uniform degree of 3?", options: ["5 vertices", "10 vertices", "15 vertices", "30 vertices"], answer: "10 vertices" },
    { id: 27, question: "The generating statement 'If P, then Q' is logically equivalent to which of the following contrapositive setups?", options: ["If Q, then P", "If not P, then not Q", "If not Q, then not P", "P and not Q"], answer: "If not Q, then not P" },
    { id: 28, question: "In a complete graph K_n containing 6 vertices, what is the exact total number of edges present?", options: ["6 edges", "12 edges", "15 edges", "30 edges"], answer: "15 edges" },
    { id: 29, question: "Which characteristic determines that a relation R on set A is 'Anti-symmetric'?", options: ["If aRb, then bRa for all choices", "If aRb and bRa, then a = b must hold true", "If aRb and bRc, then aRc must follow", "No element can map to itself directly"], answer: "If aRb and bRa, then a = b must hold true" },
    { id: 30, question: "A path in a graph G that visits every single vertex exactly once is classified as a:", options: ["Eulerian Path", "Hamiltonian Path", "Bipartite Sequence Line", "Planar Core Edge Tracker"], answer: "Hamiltonian Path" }
  ],

  "subject-mp": [
    { id: 31, question: "In the 8085 microprocessor architecture, which register pair is explicitly used as a default memory pointer reference for instructions like MOV A, M?", options: ["B and C register pair", "D and E register pair", "H and L register pair", "Program Counter (PC)"], answer: "H and L register pair" },
    { id: 32, question: "How many hardware address lines are structurally present in an 8085 microprocessor to map its physical 64 KB memory space?", options: ["8 lines", "16 lines", "20 lines", "32 lines"], answer: "16 lines" },
    { id: 33, question: "Which hardware interrupt pin in the 8085 architecture holds the absolute highest priority ranking?", options: ["TRAP (RST 4.5)", "RST 7.5", "RST 6.5", "INTR"], answer: "TRAP (RST 4.5)" },
    { id: 34, question: "What is the functional purpose of the ALE (Address Latch Enable) signal pin during an 8085 processing machine cycle?", options: ["To reset the program counter register to 0000H", "To demultiplex the low-order address and data lines (AD0-AD7)", "To freeze processor operations for external DMA transfers", "To signal an external interrupt acknowledgment loop"], answer: "To demultiplex the low-order address and data lines (AD0-AD7)" },
    { id: 35, question: "The 8086 microprocessor architecture uses which memory management layout strategy to access up to 1 MB of physical storage address space?", options: ["Direct linear flat addressing mapping", "Memory Segmentation (Segment:Offset registers)", "Virtual demand paging lookups", "Dynamic bank swapping switch gates"], answer: "Memory Segmentation (Segment:Offset registers)" },
    { id: 36, question: "Which internal register in the 8085 microprocessor structure tracks and holds the memory address of the next sequential instruction waiting to be fetched and executed?", options: ["Stack Pointer (SP)", "Instruction Register (IR)", "Program Counter (PC)", "Accumulator (Reg A)"], answer: "Program Counter (PC)" },
    { id: 37, question: "In 8085 microprocessor assembly instruction sets, the statement 'MVI A, 45H' represents which addressing mode format?", options: ["Direct Addressing Mode", "Register Addressing Mode", "Immediate Addressing Mode", "Implicit Addressing Mode"], answer: "Immediate Addressing Mode" },
    { id: 38, question: "How many general-purpose 8-bit registers are directly accessible to programmers in the 8085 design schema (excluding the accumulator)?", options: ["4 registers", "6 registers", "8 registers", "10 registers"], answer: "6 registers" },
    { id: 39, question: "Which pin status configuration flags on the 8085 chip specify that a machine cycle is processing a memory read operation explicitly?", options: ["IO/M = 1, RD = 0", "IO/M = 0, RD = 0", "IO/M = 0, WR = 0", "IO/M = 1, WR = 0"], answer: "IO/M = 0, RD = 0" },
    { id: 40, question: "What occurs to the stack pointer register content during the execution of a 2-byte 'PUSH' instruction block execution loop in an 8085 environment?", options: ["The SP register increments by 2 steps", "The SP register decrements by 2 steps", "The SP register shifts left 1 bit position", "The content remains completely unchanged"], answer: "The SP register decrements by 2 steps" },
    { id: 41, question: "How many flag bits are active inside the 8085 status flag register to provide program branching parameters?", options: ["3 flags", "5 flags", "8 flags", "16 flags"], answer: "5 flags" },
    { id: 42, question: "The 8086 microprocessor holds a prefetch instruction queue pipeline layer that can store how many bytes of data code concurrently?", options: ["4 bytes", "6 bytes", "8 bytes", "16 bytes"], answer: "6 bytes" },
    { id: 43, question: "Which hardware interrupt line on the 8085 microprocessor chip is structurally edge-triggered and level-triggered simultaneously?", options: ["TRAP", "RST 7.5", "RST 6.5", "RST 5.5"], answer: "TRAP" },
    { id: 44, question: "The instruction code layout 'ADD B' uses which category classification of processing execution targeting?", options: ["Direct Addressing Mode", "Register Addressing Mode", "Register Indirect Addressing", "Implied Targeting Format"], answer: "Register Addressing Mode" },
    { id: 45, question: "Which control bus signaling mechanism shifts data lines onto the system bus directly to allow external components to seize memory control pathways?", options: ["RESET OUT", "HOLD / HLDA", "READY state tracking line", "INTR status loop pin"], answer: "HOLD / HLDA" }
  ],

  "subject-toc": [
    { id: 46, question: "Which of the following computational language classes is fully recognized by a standard Deterministic Finite Automaton (DFA)?", options: ["Context-Free Languages (CFL)", "Regular Languages", "Context-Sensitive Languages (CSL)", "Unrestricted Recursively Enumerable Languages"], answer: "Regular Languages" },
    { id: 47, question: "The Pumping Lemma theorem is primarily applied within theoretical computer science to do which of the following tasks?", options: ["Minimize the total number of states in a complex DFA layout", "Prove that a given language is NOT regular or context-free", "Generate parsing grammar trees for compiler frontends", "Convert an NFA into an equivalent standard DFA schema"], answer: "Prove that a given language is NOT regular or context-free" },
    { id: 48, question: "Which automaton machine model holds an internal memory infrastructure structured explicitly as a Last-In, First-Out (LIFO) Stack?", options: ["Finite Automaton (FA)", "Pushdown Automaton (PDA)", "Linear Bounded Automaton (LBA)", "Standard Turing Machine Engine"], answer: "Pushdown Automaton (PDA)" },
    { id: 49, question: "According to the Chomsky Hierarchy classification model, Context-Free Grammars (CFGs) are categorized under which Type class?", options: ["Type 0 Grammar", "Type 1 Grammar", "Type 2 Grammar", "Type 3 Grammar"], answer: "Type 2 Grammar" },
    { id: 50, question: "If a Context-Free Grammar can generate two or more distinct leftmost derivation parse trees for the exact same terminal string expression, the grammar is classified as:", options: ["Regular", "Ambiguous", "Linear Connected", "Chomsky Normalized"], answer: "Ambiguous" },
    { id: 51, question: "A Turing Machine uses what type of storage architecture medium to process context string elements?", options: ["An infinite linear read/write tape framework", "A bounded LIFO call stack index", "A bidirectional circular shifting network queue", "A flash RAM virtual paging lookup matrix"], answer: "An infinite linear read/write tape framework" },
    { id: 52, question: "Regular languages maintain absolute mathematical closure conditions under which combined operational choices?", options: ["Union and intersection pathways only", "Concatenation and Kleene closure wrappers only", "Complementation matching limits only", "All operational choices listed here"], answer: "All operational choices listed here" },
    { id: 53, question: "Which automaton architecture layer recognizes Type 1 Context-Sensitive Languages (CSLs)?", options: ["Standard Non-deterministic Pushdown Automaton", "Linear Bounded Automaton (LBA)", "Universal Turing Machine System", "Deterministic Finite Automaton"], answer: "Linear Bounded Automaton (LBA)" },
    { id: 54, question: "Can a standard Deterministic Finite Automaton (DFA) track and parse the nested grammar language context L = { a^n b^n | n >= 0 }?", options: ["Yes, completely using tracking state rings", "No, due to lacking internal counting capability or infinite storage", "Only if the integer 'n' is bounded by an even index limit", "Only if it is parsed across an NFA converter module first"], answer: "No, due to lacking internal counting capability or infinite storage" },
    { id: 55, question: "Which computer science problem marks the boundary limits of decidability parameters according to Alan Turing's thesis declarations?", options: ["The Pumping Lemma proof sequence", "The Halting Problem core logic context", "The State minimization count limit", "The Ambiguity mitigation loop"], answer: "The Halting Problem core logic context" },
    { id: 56, question: "The language class recognized by a Non-deterministic Pushdown Automaton (NPDA) is exactly equivalent to which grammar class?", options: ["Regular Grammar", "Context-Free Grammar (CFG)", "Unrestricted Grammar", "Context-Sensitive Grammar"], answer: "Context-Free Grammar (CFG)" },
    { id: 57, question: "In the context of the Halting Problem, a language is classified as 'Decidable' if there exists a Turing Machine that:", options: ["Halts on all valid inputs and loops infinitely on invalid inputs", "Halts on all possible input strings and always reaches a clear True/False verdict", "Can process string items linearly without tape reversal", "Matches a regular grammar trace layout configuration"], answer: "Halts on all possible input strings and always reaches a clear True/False verdict" },
    { id: 58, question: "Which format framework strips out production rules with more than two variables on the right-hand side of a context-free grammar?", options: ["Greibach Normal Form (GNF)", "Chomsky Normal Form (CNF)", "Backus-Naur Form (BNF)", "Chomsky Type-3 standard layouts"], answer: "Chomsky Normal Form (CNF)" },
    { id: 59, question: "What is the minimum number of states required to construct a DFA that accepts any binary string ending with a specific single bit pattern like '1'?", options: ["1 state", "2 states", "3 states", "4 states"], answer: "2 states" },
    { id: 60, question: "The collection class 'Recursively Enumerable Languages' sits under which classification rank tier in the Chomsky model?", options: ["Type 0", "Type 1", "Type 2", "Type 3"], answer: "Type 0" }
  ],

  "subject-java": [
    { id: 61, question: "Consider variable allocation code: String s1 = 'BTU'; String s2 = new String('BTU'); What will expressions (s1 == s2) and s1.equals(s2) evaluate to respectively?", options: ["true, true", "false, false", "true, false", "false, true"], answer: "false, true" },
    { id: 62, question: "Where are objects explicitly allocated inside JVM memory runtime structures during Java application execution updates?", options: ["Call Stack frame tracking engine", "Globally shared Heap Memory structure", "Class Metadata Method Pool segment", "Thread Local Register Array cache spaces"], answer: "Globally shared Heap Memory structure" },
    { id: 63, question: "Which Java keyword is appended to a variable definition to turn its value cell into an unmodifiable compile-time constant?", options: ["static", "abstract", "final", "volatile"], answer: "final" },
    { id: 64, question: "In Java's exception handling infrastructure, which code block is guaranteed execution regardless of whether an exception is thrown or caught?", options: ["The try block runtime segment", "The catch exception filter block", "The finally block lifecycle pipeline", "The throws dynamic error handler marker"], answer: "The finally block lifecycle pipeline" },
    { id: 65, question: "Which collection interface variant inside the java.util package strictly forbids the insertion and tracking of duplicate element entries?", options: ["java.util.List", "java.util.Set", "java.util.Vector", "java.util.ArrayList"], answer: "java.util.Set" },
    { id: 66, question: "Does the Java language architecture support multiple inheritance directly across standard class expansion definitions?", options: ["Yes, explicitly using commas", "No, but it is cleanly achieved by implementing multiple interface structures", "Only if classes are declared as abstract models", "Only if package deployment filters are marked global"], answer: "No, but it is cleanly achieved by implementing multiple interface structures" },
    { id: 67, question: "What functional mechanism does the keyword 'synchronized' enforce when attached to a Java class method definition?", options: ["Speeds up parallel application loops across data cells", "Enforces a mutual exclusion lock across the block to prevent cross-thread race conditions", "Saves variables automatically down to localized text database sheets", "Compiles processing instructions directly to platform native machine arrays"], answer: "Enforces a mutual exclusion lock across the block to prevent cross-thread race conditions" },
    { id: 68, question: "What occurs to memory management spaces behind the scenes when an object's reference counter falls to zero inside a running JVM app?", options: ["A program crash throws a tracking stack dump flag", "The system JVM Garbage Collector tracks and clears it automatically during sweep routines", "Manual delete calls must be wired to avoid memory leak dropouts", "The variable stays locked until the system operating cache is flushed manually"], answer: "The system JVM Garbage Collector tracks and clears it automatically during sweep routines" },
    { id: 69, question: "What is the absolute root parent superclass configuration from which every user-defined class implicitly inherits in Java?", options: ["java.lang.Class", "java.lang.Object", "java.lang.System", "java.util.Collection"], answer: "java.lang.Object" },
    { id: 70, question: "Which structural map variant inside the java.util library structure coordinates item data keys securely for highly simultaneous multi-threaded operations?", options: ["java.util.HashMap", "java.util.Hashtable", "java.util.TreeMap", "java.util.LinkedHashMap"], answer: "java.util.Hashtable" },
    { id: 71, question: "What explicit compilation or runtime issue occurs if you try to modify a collection list element while iterating over it with a standard foreach loop in Java?", options: ["It triggers a ConcurrentModificationException at runtime", "It causes a permanent infinite processing lock loop", "The application throws a compile-time syntax error mismatch flag", "The array memory wipes clean automatically to avoid a thread collision"], answer: "It triggers a ConcurrentModificationException at runtime" },
    { id: 72, question: "The Java keyword 'volatile' applied to a class field attribute handles which synchronization role?", options: ["It locks the field from any writing adjustments permanently", "It forces thread updates to read/write directly from main computer RAM rather than local CPU cache lines", "It optimizes double-precision math calculations inside arrays", "It compresses text strings into byte data formats"], answer: "It forces thread updates to read/write directly from main computer RAM rather than local CPU cache lines" },
    { id: 73, question: "Which method configuration must be override declared inside a class definition to allow execution mapping across an independent Thread instantiation line?", options: ["public void start()", "public void run()", "public void execute()", "public void init()"], answer: "public void run()" },
    { id: 74, question: "What is the functional structural distinction between a checked exception and an unchecked exception in Java source architectures?", options: ["Checked exceptions are caught by the OS kernel, unchecked are caught by the application code", "Checked exceptions MUST be caught or declared at compile time, unchecked exceptions are assessed at runtime", "Checked exceptions only impact numerical operations, unchecked exceptions handle memory arrays", "There is no difference; they are evaluated using identical catch parameters"], answer: "Checked exceptions MUST be caught or declared at compile time, unchecked exceptions are assessed at runtime" },
    { id: 75, question: "Which reference modifier prevents an instantiated subclass from overriding a parent class method definition layer?", options: ["static", "final", "private", "protected"], answer: "final" }
  ],

  "subject-python": [
    { id: 76, question: "What is the evaluation output of the following sequence list operation slice configuration in Python? my_list = [10, 20, 30, 40, 50]; print(my_list[4:1:-2])", options: ["[50, 40, 30]", "[50, 30]", "[40, 20]", "[50, 40]"], answer: "[50, 30]" },
    { id: 77, question: "Which built-in structural data container type in Python is strictly immutable after its initial creation?", options: ["List structures", "Dictionary tables", "Set collections", "Tuple containers"], answer: "Tuple containers" },
    { id: 78, question: "How does Python handle structural variable scopes inside nested function layouts when resolving identifier namespaces?", options: ["Using standard bracket block alignment markers", "Via the LEGB (Local, Enclosing, Global, Built-in) rule engine", "Linear bottom-up search streams across sequential assignments", "By querying an external global dictionary pointer register file"], answer: "Via the LEGB (Local, Enclosing, Global, Built-in) rule engine" },
    { id: 79, question: "What does the keyword 'yield' explicitly do when placed inside a standard Python function scope?", options: ["Terminates active thread processing cycles immediately", "Suspends function execution state returning a Generator object iterator value", "Imports external modules dynamically inside internal namespace run steps", "Passes error handling directly down to the outer system try/catch block"], answer: "Suspends function execution state returning a Generator object iterator value" },
    { id: 80, question: "Under Python's multiple inheritance execution architecture engine, what does the acronym MRO stand for?", options: ["Memory Resource Optimization protocols", "Method Resolution Order protocols", "Main Runtime Override control sequence", "Matrix Record Allocation boundaries"], answer: "Method Resolution Order protocols" },
    { id: 81, question: "What is the correct way to copy a list dictionary shallowly in Python without linking the original variable pointer cell?", options: ["new_list = old_list", "new_list = old_list.copy()", "new_list = list(old_list)", "Both copy() and list() options copy data shallowly correctly"], answer: "Both copy() and list() options copy data shallowly correctly" },
    { id: 82, question: "What does the `*args` syntax inside a Python function signature allow a developer to do?", options: ["Pass a dictionary layout of keyword arguments", "Accept an arbitrary number of positional arguments passed as a tuple data block", "Bind pointers directly to system memory files", "Force loop operations to scale up across multi-core processors"], answer: "Accept an arbitrary number of positional arguments passed as a tuple data block" },
    { id: 83, question: "Which built-in Python tracking generator yields both the current item index and the target item value simultaneously during loop steps?", options: ["zip()", "enumerate()", "map()", "filter()"], answer: "enumerate()" },
    { id: 84, question: "What will the logical conditional comparison expression `print(bool([]))` print out on a Python terminal console?", options: ["True", "False", "None", "SyntaxError"], answer: "False" },
    { id: 85, question: "Which dunder/magic class method is executed by a Python runtime interpreter when entering a 'with' statement context manager block?", options: ["__init__", "__call__", "__enter__", "__exit__"], answer: "__enter__" },
    { id: 86, question: "How does the Python language track memory scopes and clean up variable allocations that no longer possess references?", options: ["Using manual developer delete keyword entries", "Via automatic reference counting matched with a cyclical garbage collection engine", "By running structural stack frame stripping protocols during file closures", "By pushing data flushes directly down to host RAM hardware layers"], answer: "Via automatic reference counting matched with a cyclical garbage collection engine" },
    { id: 87, question: "What occurs if you try to append a new key value pair to a standard Python dictionary while iterating over that dictionary directly with a loop?", options: ["The loop completes successfully while adjusting size bounds", "It throws a RuntimeError stating the dictionary changed size during iteration", "The compilation pipeline drops a syntax error mismatch log", "The values overwrite cell zero automatically to bypass data collisions"], answer: "It throws a RuntimeError stating the dictionary changed size during iteration" },
    { id: 88, question: "What type of data tracking object does a basic Python lambda expression construct and return?", options: ["An anonymous function object record", "A static immutable array cell tracking pointer", "A local conditional string evaluation trace", "An isolated block execution macro file"], answer: "An anonymous function object record" },
    { id: 89, question: "Which module inside the Python standard distribution library provides comprehensive tools to copy deeply nested data objects securely?", options: ["os", "sys", "copy", "json"], answer: "copy" },
    { id: 90, question: "What is the processing evaluation value of the expression `2 ** 3 ** 2` inside Python's operator precedence table rules?", options: ["64", "512", "4096", "81"], answer: "512" }
  ]
};

// ==========================================================================
// API ROUTE (Shuffles the entire 15-question concept pool)
// ==========================================================================

app.get('/api/questions/:subjectId', (req, res) => {
  const subjectId = req.params.subjectId;
  const baseQuestions = backendQuizDatabase[subjectId] || [];
  
  if (baseQuestions.length === 0) {
    return res.json([]);
  }

  let finalPool = [];

  // Loop and duplicate our high-quality base pool 4 times 
  // This instantly turns our 15 unique questions into a deep pool of 60 items!
  for (let i = 0; i < 4; i++) {
    baseQuestions.forEach(q => {
      finalPool.push({
        ...q,
        id: q.id + (i * 1000) // Ensure every duplicated question gets a unique ID tag
      });
    });
  }

  // Shuffle the combined 60-question mega pool completely
  const randomizedOutput = finalPool.sort(() => 0.5 - Math.random());
  
  res.json(randomizedOutput);
});
app.listen(PORT, '0.0.0.0', () => {
  console.log(`🛰️ Master Question Bank online on port: ${PORT}`);
});
